gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/exception/AttachmentNotFoundException.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/service/AttachmentReferenceUpdaterService.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/storage/AWSStorageService.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/storage/AzureStorageService.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/storage/LocalStorageService.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/storage/StorageManagerService.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/storage/StorageService.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/task/EhrExtractMessageHandler.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/task/MhsQueueMessageHandler.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/service/AttachmentReferenceUpdaterServiceTests.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/task/EhrExtractMessageHandlerTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/task/MhsQueueMessageHandlerTest.java
Ticket: https://gpitbjss.atlassian.net/browse/NIAD-2031
Purpose: enable documents to be downloaded via the GPC Facade
Technical details:
- added a AttachmentReferenceUpdaterService and relevant tests which for each attachment:
1.  gets the file name & when the filename is present as a "reference" in the payload xml
2. replaces the local reference to be one pulled from the storage service(s)
- added 'getFileLocation' method to storage manage and all storage specific implementations of storage service
=> Niad 2031 update fhir bundle with references

gp2gp-translator/src/integrationTest/java/uk/nhs/adaptors/pss/translator/AcknowledgeMessageHandlingIT.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/task/AcknowledgmentMessageHandler.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/task/AcknowledgmentMessageHandlerTest.java
**Acceptance Criteria** 
If the latest migration status of a transfer is `FINAL_ACK_SENT` then any further NACK message sent by the incumbent should not be processed.
=> NIAD-2582: Bugfix - NACK should not be processed for a conversation after final ack has been sent

gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP4-output.json, gp2gp-translator/src/integrationTest/resources/json/expectedBundle.json, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/medication/MedicationRequestPlanMapper.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/medication/MedicationRequestPlanMapperTest.java, gp2gp-translator/src/test/resources/xml/MedicationStatement/ehrExtract10.xml, gp2gp-translator/src/test/resources/xml/MedicationStatement/ehrExtract11.xml, gp2gp-translator/src/test/resources/xml/MedicationStatement/ehrExtract12.xml, gp2gp-translator/src/test/resources/xml/MedicationStatement/ehrExtract7.xml, gp2gp-translator/src/test/resources/xml/MedicationStatement/ehrExtract8.xml, gp2gp-translator/src/test/resources/xml/MedicationStatement/ehrExtract9.xml
**Description**
We were expecting the term Expired to be here without the “True“ prefixing it, please investigate, confirm the logic with Martin Hillyard and fix if required following the discussion. 
**Investigation**
There was a coding error that inserted the Boolean value. However, the string itself was constructed from the discontinue's pertinent annotation, code and availability time. After discussion with Martin, it was decided a better approach was to use the pertinent information or a default string of "No information available", as per the GP Connect spec.
*Additional changes were identified as a result of the investigation:*
- If a discontinue request is present and it's possible to map the status reason extension, the status of the medication request should be `stopped`.  
- If …
=> Niad-2509: bugfix - medication request prepended true

db-connector/changelog/migration/12-add-processedlength-column-to-patient_attachment-log-table.xml, db-connector/src/main/java/uk/nhs/adaptors/connector/dao/PatientAttachmentLogDao.java, db-connector/src/main/java/uk/nhs/adaptors/connector/mapper/PatientAttachmentLogRowMapper.java, db-connector/src/main/java/uk/nhs/adaptors/connector/model/PatientAttachmentLog.java, db-connector/src/main/java/uk/nhs/adaptors/connector/service/PatientAttachmentLogService.java, db-connector/src/main/resources/uk/nhs/adaptors/connector/dao/PatientAttachmentLogDao/insert_patient_attachment_log.sql, db-connector/src/main/resources/uk/nhs/adaptors/connector/dao/PatientAttachmentLogDao/update_patient_attachment_log.sql, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP7_vis-output.json, gp2gp-translator/src/integrationTest/resources/json/LargeMessage/expectedBundleScenario1.json, gp2gp-translator/src/integrationTest/resources/json/LargeMessage/expectedBundleScenario2.json, gp2gp-translator/src/integrationTest/resources/json/LargeMessage/expectedBundleScenario3.json, gp2gp-translator/src/integrationTest/resources/json/LargeMessage/expectedBundleScenario4.json, gp2gp-translator/src/integrationTest/resources/json/LargeMessage/expectedBundleScenario6.json, gp2gp-translator/src/integrationTest/resources/json/LargeMessage/expectedBundleScenario8.json, gp2gp-translator/src/integrationTest/resources/json/LargeMessage/expectedBundleScenario9.json, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/DocumentReferenceMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/service/BundleMapperService.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/service/InboundMessageMergingService.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/task/COPCMessageHandler.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/task/EhrExtractMessageHandler.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/DocumentReferenceTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/service/BundleMapperServiceTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/service/InboundMessageMergingServiceTests.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/task/COPCMessageHandlerTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/task/EhrExtractMessageHandlerTest.java
Url is already present in the output, but length is not considered.
Updated db-connector with migration to store a post processed length field in the patient attachment log (as length num field is used for validation if length is provided in source)
Updated GP2GP translator to calculate lengths based on payload size and the bundle to display this as size
=> NIAD-2489 Mapping Bug PWTP7: Document Reference does not have url or length parameters.

gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP10-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP11-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP2-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP3-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP4-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP7_vis-output.json, gp2gp-translator/src/integrationTest/resources/json/expectedBundle.json, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/medication/MedicationMapperUtils.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/medication/MedicationRequestPlanMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/medication/MedicationStatementMapper.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/medication/MedicationStatementMapperTest.java, gp2gp-translator/src/test/resources/xml/MedicationStatement/ehrExtract_authorise_effectiveTimeHigh.xml, gp2gp-translator/src/test/resources/xml/MedicationStatement/ehrExtract_discontinue.xml, gp2gp-translator/src/test/resources/xml/MedicationStatement/ehrExtract_discontinueMissingAvailabilityTime.xml, gp2gp-translator/src/test/resources/xml/MedicationStatement/ehrExtract_discontinue_noValidTimes.xml, gp2gp-translator/src/test/resources/xml/MedicationStatement/ehrExtract_effectiveTimeHigh.xml, gp2gp-translator/src/test/resources/xml/MedicationStatement/ehrExtract_noValidTimes.xml
**Description**
At the moment Medication Statements in a state of completed has no end date which is only valid in the case of an active Mediciation Statement. 
Fix: If state is in a valid `stopped` / `completed` state. The `effectivePeriod.end` date should be set to the `AvailabilityTime` found in the related `EHRSupplyDiscountinue` HL7 data.
**Implementation details**
As a GP2GP `MedicationStatement` with a status of `complete` may or may not have a `ehrSupplyDiscontinue` component the following logic has been implemented to ensure an end date is mapped:
set `medicationStatement.effectiveperiod.end` date to (in preference order): 
1. The availability time in the `EhrSupplyDiscontinue`.
2. The High value of the effective time element in the `Ehrsupplyauthorise`.
3. The High value of the …
=> NIAD-2508: bug fix: medication statement end date

gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP9-output.json, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/util/ObservationUtil.java
Under Resource Type Observation the the data item valueQuantity has a field called “comparator“. This needs to be removed…
"valueQuantity": {
"value": 1000.000,
"comparator": ">=",
"unit": "ng/L"
},
Update ObservationUtil to remove comparator if ValueQuantity mapper adds 
Update expected PWTP9 output for E2E Tests to ensure comparator is not set for observations
=> NIAD-2576: Mapping Bug PWTP9 - Reference range comparators is not a supported item in FHIR

gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP9-output.json, gp2gp-translator/src/integrationTest/resources/json/expectedBundle.json, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/diagnosticreport/DiagnosticReportMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/diagnosticreport/SpecimenCompoundsMapper.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/diagnosticreport/SpecimenCompoundsMapperTest.java
Diagnostic report is incorrectly referencing all observations instead of just the primary parent observation
=> Niad-2612: bugfix diagnostic report result referencing

README.md, gpc-api-facade/src/main/java/uk/nhs/adaptors/pss/gpc/controller/PatientTransferController.java
If the following headers are present in the Migrate Structured Request, the adaptor currently accepts blank values. These are then inserted into to EHR Request.
- `to-asid`
- `from-asid`
- `to-ods`
- `from-ods `
In order to prevent this, the headers should be validated to ensure they are not empty or effectively empty (whitespace only).
=> Niad 2644: bugfix - empty migrate structured headers

gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/DocumentReferenceMapper.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/DocumentReferenceTest.java, gp2gp-translator/src/test/resources/xml/DocumentReference/narrative_statement_null_flavors.xml, test-suite/docker-compose.yml, test-suite/docker/docker-compose.yml
If the ehrComposition has an availabiltyTime but this has no value then an exception will be thrown trying to parse to the DateTimeType. This should be handled by checking that the it has an availabilityTime and that the value is not null, before attempting to parse to datetime
=> NIAD-2640: bugfix - document ref - createdTime throws if nullFlavor

gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/BloodPressureMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/ObservationMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/diagnosticreport/SpecimenMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/util/BloodPressureValidatorUtil.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/util/CDUtil.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/util/CodeUtil.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/util/ResourceFilterUtil.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/util/BloodPressureValidatorUtilTest.java, gp2gp-translator/src/test/resources/xml/BloodPressure/triple_with_snomed.xml, gp2gp-translator/src/test/resources/xml/BloodPressure/triple_with_snomed_translation.xml, gp2gp-translator/src/test/resources/xml/BloodPressure/triple_without_snomed.xml
Problem seen with Consultations 2 dataset. 
- Blood pressure parent should be included in the appropriate Encounter List, this is not currently the case in the PS.
The root cause of this was that in the Consultations 2 dataset, the SNOMED codes are nested inside the code element as translations. The PS Adaptor didn't support this nested structure for blood pressures and as a result mapped them incorrectly. 
The issue was also present for  diagnostic report and allergy mappings. Diagnostic reports have been updated as part of this ticket. Allergies were already raised in a separate ticket ([NIAD-2617](https://gpitbjss.atlassian.net/browse/NIAD-2617))
=> NIAD-2648: bugfix - blood pressure parent missing

gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/storage/StorageManagerService.java, gp2gp-translator/src/main/resources/application.yml
**Storage Service log messages fix**
Log messages for storage service retries should be of the form: 
“(retryAttempt + 1) of (retryLimit)” 
i.e. “1 of 3” instead of “0 of 3”
---
**Storage Retry Environment variable name**  
Change STORAGE_RETRY_Limit to STORAGE_RETRY_LIMIT
=> NIAD-2687: int_14 minor fixes

gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/service/InboundMessageMergingService.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/service/InboundMessageMergingServiceTests.java
If bundle mapping fails after merging attachments, NACK EHR with code 21
=> NIAD-2713: Bugfix - bundle mapping exception should send NACK code 21

test-suite/daisy-chaining/docker-compose.yml, test-suite/daisy-chaining/start-daisy-chain-environment.sh, test-suite/daisy-chaining/vars-versions.sh, test-suite/start-test-environment.sh, test-suite/vars-versions.sh
As we have pushed new images to Docker Hub the default test suite images are out of date. There are also unused and duplicate environment variables for the images in `test-suite/vars-versions.sh` and  `test-suite/daisy-chaining/vars-versions.sh`.
- Update the default image variables to the latest versions. 
- Tidy up the scripts to remove duplication
- Update the daisy chaining docker-compose  file to use images for the PS Adaptor, as the changes necessary  to enable daisy chaining have now been released
- Remove coloured text from the start environment scripts as it wasn't displayed correctly in a WSL Ubuntu shell
=> Update test suite container versions and tidy up scripts.

gp2gp-translator/src/nonFunctionalTest/TestPlans/PS_NF_REL_1/PS_NF_REL_1.jmx, gp2gp-translator/src/nonFunctionalTest/TestPlans/PS_NF_REL_1/config.properties, gp2gp-translator/src/nonFunctionalTest/TestPlans/PS_NF_REL_2/PS_NF_REL_2.jmx, gp2gp-translator/src/nonFunctionalTest/TestPlans/PS_NF_STR_1/PS_NF_STR_1.jmx, gp2gp-translator/src/nonFunctionalTest/TestPlans/PS_NF_STR_1/config.properties, gp2gp-translator/src/nonFunctionalTest/TestPlans/PS_NF_STR_2/PS_NF_STR_2.jmx, gp2gp-translator/src/nonFunctionalTest/TestPlans/PS_NF_STR_2/config.properties, gp2gp-translator/src/nonFunctionalTest/TestPlans/PS_NF_STR_3/PS_NF_STR_3.jmx, gp2gp-translator/src/nonFunctionalTest/TestPlans/PS_NF_STR_3/README.md, gp2gp-translator/src/nonFunctionalTest/TestPlans/PS_NF_STR_3/build-test-environment.sh, gp2gp-translator/src/nonFunctionalTest/TestPlans/PS_NF_STR_3/config.properties, gp2gp-translator/src/nonFunctionalTest/TestPlans/PS_NF_STR_3/docker-compose.yml
Add facadeUrl as configuration property
ensure jndi.properties has property for url
update tests to use facadeUrl property
update build script to create network for local test from multiple GP2GP adaptors
=> NIAD 2737: Update JMeter to prepare for AWS testing

docker/docker-compose-arm.yml
The docker deployment script now works on ARM cpu architectures.
=> Fixed ARM docker deployment script.

gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP10-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP3-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP5-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP6-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP7_vis-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP9-output.json, gp2gp-translator/src/integrationTest/resources/json/expectedBundle.json, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/BloodPressureMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/ConditionMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/DocumentReferenceMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/EncounterMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/ObservationMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/TemplateMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/diagnosticreport/SpecimenBatteryMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/util/DegradedCodeableConcepts.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/BloodPressureMapperTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/ConditionMapperTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/DocumentReferenceTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/EncounterMapperTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/ObservationMapperTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/TemplateMapperTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/diagnosticreport/SpecimenBatteryMapperTest.java
If a coding block does not contain a Snomed entry (but may contain one or more non-Snomed codes) it should generate a degraded resource.
These changes add the respective degraded code to all resources which map codeableConcepts using the codeableConceptMapper.
Details of degraded codes are detailed in section 3 of the following document:
[Guidance On CodeableConcept](https://developer.nhs.uk/apis/gpconnect-1-6-0/pages/accessrecord_structured/GuidanceOnCodeableConcept.pdf)
=> NIAD-2817: Degrade codes are not mapped for all resources

CHANGELOG.md, developer-information.md, release-scripts/release.sh
This adds a change log to the repository for the Github releases.
It also adds a release script, taking the steps required from the developer documentation, and updates the developer documentation to reflect this.
To ensure details of a releases are captured, which alongside the documentation and release script will help to improve the efficiency of the release process.
=> Add change log and release scripts

CHANGELOG.md, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mhs/MhsRequestBuilder.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/model/ContinueRequestData.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/service/ApplicationAcknowledgementMessageService.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/service/ContinueRequestService.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/service/EhrExtractRequestService.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/task/EhrExtractMessageHandler.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/task/SendACKMessageHandler.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/task/SendContinueRequestHandler.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/task/SendEhrExtractRequestHandler.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/task/SendNACKMessageHandler.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/util/template/parameter/SendContinueRequestParams.java, gp2gp-translator/src/main/resources/templates/sendContinueRequest.mustache, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/service/ApplicationAcknowledgementMessageServiceTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/service/ContinueRequestServiceTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/service/EhrExtractRequestServiceTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/task/EhrExtractMessageHandlerTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/task/SendACKMessageHandlerTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/task/SendContinueRequestHandlerTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/task/SendEhrExtractRequestHandlerTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/task/SendNACKMessageHandlerTest.java, gp2gp-translator/src/test/resources/xml/COPC_IN000001UK01_CONTINUE/payload.xml
- Add fixed value attributes to the continue message, as the MIM states they should be included.
- Reference the EHR extract in the continue message's ACK payload
- Send `Message-Id` header in all requests sent to the MHS Outbound service
- To fix an issue where the GP2GP Continue Message was not accepted by EMIS. 
=> NIAD-2832: Fix continue message not being accepted by EMIS

.dockerignore, CHANGELOG.md, Jenkinsfile, OPERATING.md, docker/snomed-schema/Dockerfile, release-scripts/release.sh
Add database requirements section to Operating Document.
In the process, publish the SNOMED schema Docker image to DockerHub so that we can reference it within the instructions.
=> NIAD-2781: Operating Document - Database requirements

OPERATING.md, README.md
The content has been plagiarised from the GP2GP adaptor.
I'm not clear if there's anything more to add for now, so happy to take a steer from @benhession.
=> Add MQ section to OPERATING.md

CHANGELOG.md, developer-information.md, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/storage/AWSStorageService.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/storage/AzureStorageService.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/storage/LocalStorageService.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/storage/StorageServiceFactoryConfig.java
Enable S3 connections when using an AWS instance role. 
The current implementation always requires user credentials. The change allows credentials to be used when they are provided, otherwise attempts a connection without. This makes it possible for authorisation to be configured via an AWS Instance role.     
=> Enable AWS instance roles for S3

CHANGELOG.md, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/service/AttachmentReferenceUpdaterService.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/service/AttachmentReferenceUpdaterServiceTests.java, gp2gp-translator/src/test/resources/xml/RCMRIN030000UK06_LARGE_MSG/expected_encoded_urls.xml
Fix issue where the incorrect object storage URLs were inserted into the EHR prior to mapping
An identical URL was inserted into the mapped bundle for every document. Therefore, the correct document would not be retrieved from Object Storage. 
=> NIAD-2874: Bug Fix - duplicate attachment URLs

CHANGELOG.md, db-connector/src/main/java/uk/nhs/adaptors/connector/model/PatientAttachmentLog.java, db-connector/src/test/java/uk/nhs/adaptors/connector/model/PatientAttachmentLogTest.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/service/AttachmentHandlerService.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/task/COPCMessageHandler.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/util/XmlParseUtilService.java, gp2gp-translator/src/main/resources/application.yml, gp2gp-translator/src/main/resources/logback.xml
Update the code that builds the file description when an attachments metadata is re-built from the database.  Refactor the code to reduce duplication of this functionality.
Enable logging for migration status updates using `PS_LOGGING_LEVEL`.
Compressed large attachments are not decompressed when uploading to object storage. This is due to the description being re-build incorrectly i.e. `Compressed=true` instead of  `Compressed=Yes`.  The skeleton attribute was also re-built incorrectly as `DomainData=”\X-GP2GP-Skeleton:Yes\”` where the documentation states it should be `DomainData=”X-GP2GP-Skeleton: Yes`.
SA testing have requested the migration status updates to be printed to the logs. This was already present but not configurable via the environment variables. 
Please delete options …
=> NIAD-2777: Bug Fix - attachments not decompressed

gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/sds/SdsRequestBuilder.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/service/SDSService.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/service/SDSServiceTest.java
By this PR we are adapting the way how we query SDS service to avoid getting a broken response.
When querying the SDS service and sending ODS and identifier params we get some sections  of the response empty which  causes some workflow issues. The ITOC team couldn't provide any solutions that could resolve the issue. There are some alternative endpoints that we can use and find the workaround and that's what this PR is bringing.
=> NIAD-2873: changing the way how we querying SDS service

gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/sds/SdsRequestBuilder.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/service/SDSService.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/service/SdsClientService.java
Improve the logging information for SDS requests
There are now two different requests made to SDS. Previously you'd see the same line repeated twice:
```
2023-10-17 11:42:51.522 Level=DEBUG Logger=u.n.a.p.t.service.SdsClientService ConversationId=AE68494E-D91E-445B-AE9B-B164C747B985 Thread="scheduling-1" Message="Sending request to SDS"
2023-10-17 11:42:51.903 Level=DEBUG Logger=u.n.a.p.t.service.SdsClientService ConversationId=AE68494E-D91E-445B-AE9B-B164C747B985 Thread="scheduling-1" Message="Sending request to SDS"
```
This makes the two lines clearer.
=> Improve the logging information for SDS requests

CHANGELOG.md, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP10-output.json, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/AllergyIntoleranceMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/util/AuthorUtil.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/util/ParticipantReferenceUtil.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/AllergyIntoleranceMapperTest.java, gp2gp-translator/src/test/resources/xml/AllergyIntolerance/allergy-structure-with-author-and-multiple-participants.xml, gp2gp-translator/src/test/resources/xml/AllergyIntolerance/allergy-structure-with-participant-of-aut-typecode.xml, gp2gp-translator/src/test/resources/xml/AllergyIntolerance/allergy-structure-with-valid-author-and-participant2.xml
This PR maps author and participant to recorder and asserter fields in JSON bundle. 
From XML input we are mapping author and participant entries (if both are present) to recorder and asserter fields in JSON bundle response otherwise it will populate recorder and asserter fields with data from participant.
This change was done to change the case when recorder and asserter fields were always populated with participants data no matter whether author were present or not.
- [x ] Bug fix (non-breaking change which fixes an issue)
=> NIAD-2869: mapping author and participant to recorder and asserter in JSON bundle

OPERATING.md
Add a section to OPERATING.md for the Timeout functionality
The NME must configure the timeout functionality correctly to end "stuck" transfers.
=> NIAD-2785: Add timeout section to operating doc

gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/amqp/JmsListenerErrorHandler.java
increase `JmsListenerErrorHandler` log severity to error
An severity of error is more appropriate. 
=> increase JmsListenerErrorHandler log severity to error

OPERATING.md
Update the object storage section of the operating document.
An issue arose where an NME had not set the access permissions appropriately for the adaptor. Therefore, this section has been added for clarity. 
The existing section has been refactored and added to to ensure the supplier is aware of what is stored in object storage and that it is their responsibility to maintain it,   
=> NIAD-2779:  Document which permissions are required for the Object Storage

CHANGELOG.md, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/task/AcknowledgmentMessageHandler.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/task/AcknowledgmentMessageHandlerTest.java
Ignore acknowledgement messages for a migration that has entered a failed state. 
The adapter can currently transition from a failed state to an in-progress state when an acknowledgment is received. 
=> NIAD-2908: bug fix - invalid state transition

OPERATING.md, developer-information.md
I've moved any previous documentation into one central location within OPERATING.md
Links to that have been added where useful.
So our end users can understand what variables exist, what their purpose is and how to set them.
=> NIAD-2786: Document all adaptor environment variables

CHANGELOG.md
=> Updated changelog for version 0.16

test-suite/README.md, test-suite/docker-compose.yml, test-suite/start-test-environment.sh
Importing the SNOMED data takes a very long time.
Avoid this by:
- Storing PostgreSQL data within a docker volume.
- Checking the existance of the data before importing the SNOMED data
**Could I ask that a reviewer checks that the behaviour works on Windows too? I have tested on Mac fine.**
=> test-suite: Avoid importing SNOMED data where possible

release-scripts/release.sh
This helps link the container back to this repoistory, and is a standardised annotation.
https://github.com/opencontainers/image-spec/blob/main/annotations.md
=> Add org.opencontainers.image.source label to released Dockerhub images

OPERATING.md, README.md, developer-information.md
When moving the guidance, instead of referencing running shell scripts instead use the existing Docker execution guidance within the document.
This file should contain all technical operating information that an end user needs to know.
We already had some SNOMED information within OPEARTING.md, so this consolidates it into one place.
=> Consolidate the SNOMED database information into OPERATING.md

README.md
Replace README Developer Information section with Table of contents
The existing Developer Information felt like some links out to other documents.
Having a clear table of contents feels like a clearer way of achieving the same outcome.
=> Replace README Developer Information section with Table of contents

gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/AgentDirectoryMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/DocumentReferenceMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/storage/AzureStorageService.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/util/ObservationUtil.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/util/ResourceReferenceUtil.java
Methods in mappers return null which potentially can cause NPE, also there is a safer version of try-catch introduced: try-with-resources
When method returns null instead of an empty collection it will propagate nulls into other places in code and can potentially trigger NPE. It is better and safer to return an empty collection. Also, try-with-resources will make sure that the steam will be always closed not matter what.
=> Eliminating possible NPE + adding safer try--with-resources version + small code cleanup

test-suite/vars-versions.sh
=> test-suite: Update versions of PS Adaptor + MHS to latest releases

CHANGELOG.md, OPERATING.md, developer-information.md, release-scripts/release.sh
=> Add release 1.1.0

gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP10-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP11-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP2-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP3-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP4-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP5-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP6-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP7_vis-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP9-output.json, gp2gp-translator/src/integrationTest/resources/json/LargeMessage/expectedBundleScenario1.json, gp2gp-translator/src/integrationTest/resources/json/LargeMessage/expectedBundleScenario10.json, gp2gp-translator/src/integrationTest/resources/json/LargeMessage/expectedBundleScenario11.json, gp2gp-translator/src/integrationTest/resources/json/LargeMessage/expectedBundleScenario2.json, gp2gp-translator/src/integrationTest/resources/json/LargeMessage/expectedBundleScenario3.json, gp2gp-translator/src/integrationTest/resources/json/LargeMessage/expectedBundleScenario4.json, gp2gp-translator/src/integrationTest/resources/json/LargeMessage/expectedBundleScenario5.json, gp2gp-translator/src/integrationTest/resources/json/LargeMessage/expectedBundleScenario6.json, gp2gp-translator/src/integrationTest/resources/json/LargeMessage/expectedBundleScenario7.json, gp2gp-translator/src/integrationTest/resources/json/LargeMessage/expectedBundleScenario8.json, gp2gp-translator/src/integrationTest/resources/json/LargeMessage/expectedBundleScenario9.json, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/AgentDirectoryMapper.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/AgentDirectoryMapperTest.java, gp2gp-translator/src/test/resources/xml/AgentDirectory/agent_org_with_general_practitioner_number.xml
Practitioner GP Number Field Missing from FHIR Output
GP Number Field that is included in agentDirectory section doesn't appear in FHIR Output Practitioner section. This PR adds this information into Practitioner section.
=> NIAD-2772: adding identifier block to practitioner section

CHANGELOG.md, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP10-output.json, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/AllergyIntoleranceMapper.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/AllergyIntoleranceMapperTest.java
The order of fields in which we pull recorder and asserter (author and practitioner) have been requested to be changed.
Before the change we pulled author XML field and assigned it to asserter and practitioner XML field and assigned it to recorder. It was not the order of pulling fields and it was requested to be changed which was addressed in this PR.
=> NIAD-2921: fixing asserter and recorder fields

db-connector/gradlew, gp2gp-translator/gradlew, gpc-api-facade/gradlew, gradlew, smoke-tests/gradlew, smoke-tests/gradlew.bat, test-suite/mock-spine-mhs-outbound/gradlew, test-suite/mock-spine-mhs-outbound/gradlew.bat
Memory increase for different PS adaptor components
Different PS Adaptor components need enough memory for sufficient performance.
Some Gradle setup is responsible for running tests/integration tests, so this setup change should make JVM that runs it more sufficient and not limited in memory.
=> Memory increase for better components performance

README.md
Readme update about OperationOutcome error output
The readme section didn't have the latest change to OperationOutcome section where specific GP2GP error code output was added hence this change fixes it.
=> Update OperationOutcome example in README with new GP2GP code

CHANGELOG.md, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/ReferralRequestMapper.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/ReferralRequestMapperTest.java, gp2gp-translator/src/test/resources/xml/RequestStatement/nested_request_statement.xml, gp2gp-translator/src/test/resources/xml/RequestStatement/request_statement_missing_priority_code.xml, gp2gp-translator/src/test/resources/xml/RequestStatement/request_statement_unexpected_priority_code.xml, gp2gp-translator/src/test/resources/xml/RequestStatement/two_nested_request_statements.xml
Map a referral request's priority from the request statement's priority code element. Remove unnecessary recursive method.
- If the priority code is not provided or not recognised as an `EhrReferralPriority` code. Do not populate the referral request's priority
Conversation ID = `018C3F38-A5D9-727E-AE60-E5B94933480C` (2023-12-06 13:02:10.282) from EMIS to Medius 
The mapping of the EHR Extract failed due to a null pointer in the Referral Request mapper. Specifically when mapping the priority code. 
The method causing the null pointer was recursively searching for a request statement with a priority code. However, the mapped request statement is already available in the call stack. There is no documented reason why the recursive search is required.   
**Note:** the priority codes original …
=> NIAD-2972: bugfix - Referral request priority code null pointer 

docker/gp2gp-translator/Dockerfile, docker/gpc-facade/Dockerfile
We appear to be hitting https://github.com/netty/netty/issues/12343
Note that this defect only appears to happen when running inside of the AWS path to live environment. When run locally, the adaptor doesn't run into this codepath.
Will investigate an upgrade to Netty in a future PR
=> Revert back to Ubuntu focal

developer-information.md
Add a smoke test step as part of the release process
As part of release 1.3.0 we had an issue where the image failed to boot in AWS.
This smoke test will prove that the adaptor can work end to end before a release.
=> Add a smoke test step as part of the release process 

CHANGELOG.md, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/service/RequestBuilderService.java
REST buffer limit update
REST buffer size should be sufficient to accommodate the heavy messages that PS Adaptor might be given to translate
=> REST client buffer limit update

CHANGELOG.md, gp2gp-translator/src/integrationTest/resources/json/LargeMessage/expectedBundleScenario1.json, gp2gp-translator/src/integrationTest/resources/json/LargeMessage/expectedBundleScenario2.json, gp2gp-translator/src/integrationTest/resources/json/LargeMessage/expectedBundleScenario3.json, gp2gp-translator/src/integrationTest/resources/json/LargeMessage/expectedBundleScenario4.json, gp2gp-translator/src/integrationTest/resources/json/LargeMessage/expectedBundleScenario5.json, gp2gp-translator/src/integrationTest/resources/json/LargeMessage/expectedBundleScenario6.json, gp2gp-translator/src/integrationTest/resources/json/LargeMessage/expectedBundleScenario7.json, gp2gp-translator/src/integrationTest/resources/json/LargeMessage/expectedBundleScenario8.json, gp2gp-translator/src/integrationTest/resources/json/LargeMessage/expectedBundleScenario9.json, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/AgentDirectoryMapper.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/AgentDirectoryMapperTest.java
Also output the URI as opposed to the OID
~~We've seen some records within the E2E tests folder which don't have an explicit code system specified.
The MiM states that the codeSystem will be SNOMED.
If the adaptor gets an Agent which is missing a codeSystem, default it to SNOMED.~~
When mapping the code system, we are populating the system code and not the code system (ie. http://...).  This should be populating the code system.
It has been unclear on what to do when the code system is missing, i.e. just a code is provided, so at present we are mapping this, and not providing a code system.  This may need to be reviewed further @adrianclay 
https://github.com/NHSDigital/patient-switching-adaptors-mapping-documentation/pull/36
[mapping-docs]: …
=> NIAD-2989: When mapping PractitionerRole and OrganizationRoles populate the systemcode

CHANGELOG.md, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/ProcedureRequestMapper.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/ProcedureRequestMapperTest.java, gp2gp-translator/src/test/resources/xml/ProcedureRequest/ehr_extract_author_time_example.xml
https://github.com/NHSDigital/patient-switching-adaptors-mapping-documentation/pull/37
=> NIAD-2954: Use ehrComposition / author for authoredOn field instead of ehrExtract / availabilityTime

CHANGELOG.md, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP5-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP6-output.json, gp2gp-translator/src/integrationTest/resources/json/expectedBundle.json, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/AllergyIntoleranceMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/ImmunizationMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/util/ParticipantReferenceUtil.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/ImmunizationMapperTest.java, gp2gp-translator/src/test/resources/xml/Immunization/immunization_with_ehr_composition_with_author_and_participant.xml, gp2gp-translator/src/test/resources/xml/Immunization/immunization_with_ehr_composition_with_one_observation_participant.xml
Assigning role to a practitioner who records vaccinations.
The roles of practitioners are not recorder in transfers hence it is difficult to identify who recorded a vaccination.
=> NIAD-2957: adding different practitioners to immunization

CHANGELOG.md, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP9-output.json, gp2gp-translator/src/integrationTest/resources/json/expectedBundle.json, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/diagnosticreport/SpecimenCompoundsMapper.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/diagnosticreport/SpecimenCompoundsMapperTest.java
Remove the functionality for this mapping and updated unit / integration tests accordingly
When `Filing Comments` are present when mapping a `Test Group Header` or `Test Result` they were referenced using the relationship field to provide a `has-member` relationship.  This was not the correct behaviour as listed in the [GP Connect documentation](https://developer.nhs.uk/apis/gpconnect-1-6-0/accessrecord_structured_development_observation_testResult.html#related)
=> NIAD-2962: PS Adaptor incorrectly includes "Filing Comments" in the "related" property of Observation FHIR resources

docker/gp2gp-translator/Dockerfile, docker/gpc-facade/Dockerfile, gp2gp-translator/build.gradle, gpc-api-facade/build.gradle, gpc-api-facade/src/integrationTest/resources/application.yml, gpc-api-facade/src/main/resources/application.yml
This fixes a few CVEs, but also upgrades the version of netty to one which doesn't suffer from Ubuntu Jammy incompatbility.
See also baf8f71
Dependency upgrade! 🚀
=> NIAD-3027: Upgrade Spring Boot to 2.7 branch

Jenkinsfile
We're currently seeing "disk space" errors on Jenkins worker nodes.
Removing volumes as part of the post-build cleanup will hopefully reduce the frequency of cleanup of this error.
=> Jenkins: Remove volumes too

CHANGELOG.md, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP10-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP11-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP2-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP3-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP4-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP6-output.json, gp2gp-translator/src/integrationTest/resources/json/expectedBundle.json, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/ProcedureRequestMapper.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/ProcedureRequestMapperTest.java
Previously the adaptor had a fixed value of `Active` for Plan Statements, this has now been changed so that the following mapping occurs when `PlanStatement.text` starts with `Status:`:
`Status: Pending` -> `active`
`Status: Cancelled by clinician` -> `cancelled`
`Status: Superseded` -> `cancelled`
`Status: Seen` -> `completed`
When `PlanStatement.text` is not present or does not not start with `Status:` then a fallback of `unknown` is used.
The adaptor has a fixed value of `Status: active` for Plan Statements, but this does not reflect the status being returned by **SystmOne**.   When a recall is generated by **SystmOne** they consistently provide a value for `PlanStatement.text` with starts with 'Status: `; The value immediately following this should be used to set the appropriate …
=> NIAD-3038 & 3039: Plan Statement (Recall) Statuses

CHANGELOG.md, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/ConditionMapperTest.java
Improving the naming of some methods for OnsetDateTime.
=> NIAD-3058: improving naming convention and changelog

gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/ConditionMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/util/CodeableConceptUtil.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/ConditionMapperTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/util/CodeableConceptUtilTest.java, gp2gp-translator/src/test/resources/xml/Condition/linkset_pertinentInformation.xml, gp2gp-translator/src/test/resources/xml/Condition/linkset_pertinentInformation_with_3_observationStatements.xml, gp2gp-translator/src/test/resources/xml/Condition/linkset_pertinentInformation_with_different_observation_statements.xml
Codeable concept validation
We should be able to validate codeable concepts and their subelements and check whether they are identical which can be used in different scenarios.
=> Niad-3067: codeable concept validation

gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/util/CodeableConceptUtil.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/util/CodeableConceptUtilTest.java
=> NIAD-3067: codeable concept changes

gpc-api-facade/build.gradle
We don't have any direct dependency on this package, so removing.
=> Remove the JUnit Platforms Commons dependency

common/src/main/java/uk/nhs/adaptors/common/util/OidUtil.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/util/OidUtilTest.java
Add util class and associated tests to check / parse if a string is an OID
As part of [NIAD-2848](https://nhse-dsic.atlassian.net/browse/NIAD-2848) it is required to check and return an string value as a URN (ie: `"urn:oid:1.2.3.4.5"`) if it is a valid OID.  This util class is introduced to allow this check to be completed in multiple places
- A valid OID is determined to be a string of only numerical elements separated by `.`. 
- As an OID is used to represent a hierarchical structure, there could be any amount of elements each separated by `.`.
- An OID will not end in a `.`.
- An OID will start with the numerical value 0, 1 or 2.
- An OID will contain at least 2 elements.
- The second element will not be `0` if the OID only has two elements (ie: `1.0` is not valid, whereas `1.1` is) …
=> Add util class to check / parse if a string is an OID

gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/ConsultationListMapper.java
- [ x] Bug fix (non-breaking change which fixes an issue)
- [x ] I have performed a self-review of my code
=> Need to check author date time exists to stop null pointer access.

gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/storage/LocalStorageService.java
Flaky test errors are harder to interpret with the current error:
```
Caused by: java.lang.NullPointerException: Cannot read the array length because "buf" is null
```
=> Improve error for downloading non-existent file from LocalStorageService

docker/db-migration/Dockerfile, docker/gp2gp-translator/Dockerfile, docker/gpc-facade/Dockerfile
These docker images already have the correct version of gradle installed.
Using the wrapper means that another copy of gradle gets downloaded which is wasteful given we already have the correct version available.
This should speed up the building of these images.
=> Use gradle command instead of wrapper inside of Docker

CHANGELOG.md, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP9-output.json, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/ObservationCommentMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/diagnosticreport/DiagnosticReportMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/diagnosticreport/SpecimenMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/service/BundleMapperService.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/diagnosticreport/DiagnosticReportMapperTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/diagnosticreport/SpecimenMapperTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/service/BundleMapperServiceTest.java
Having Mapping out the TPP and current adaptor behaviour, we have identified the differences between the mapping.  Discussed this further and it appears that the behaviour should be:
* If a comment note narrative statement appears at the a diagnostic report level, then this should be referenced to in the result references.  This observation is determined to be the filing comment
* If there is no comment not narrative statement at diagnostic report level, the it could appear in one or more nested “battery” results.  In this case a new observation comment should be created to be used as the filing comment and referenced to in the results references.  This observation filing comment should not contain a comment text field.
This is a breaking change as it will be adding new references to the …
=> NIAD-2666: Battery Level Filing Comments should be referenced from DiagnosticReport

CHANGELOG.md, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP9-output.json, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/diagnosticreport/DiagnosticReportMapper.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/diagnosticreport/DiagnosticReportMapperTest.java
=> Set status to 'unknown' for filing comments

gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/QuantityMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/util/MeasurementUnitsUtil.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/util/ObservationUtil.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/BloodPressureMapperTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/ObservationMapperTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/QuantityMapperTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/util/ObservationUtilTest.java, gp2gp-translator/src/test/resources/xml/Observation/ivl_pq_value_quantity_observation_example.xml, gp2gp-translator/src/test/resources/xml/Observation/pq_value_quantity_observation_example.xml
Refactor QuantityMapper and MeasurementUtils to be fully static and update unit tests accordingly
QuantityMapper and MeasurementUtils were better suited to be used as statics rather than as services and they were only being used in a static fashion.  Unit tests ontained workarounds to retrieve, change accessablity and mock responses.  This lead to messy tests to much bloat.  As the QuantityMapper and MeasurementUtils class were already tightly coupled, it made sense to refactor these accordingly
=> Refactor QuanityMapper and MeasurementUtils to be fully static

CHANGELOG.md, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP9-output.json, gp2gp-translator/src/integrationTest/resources/json/expectedBundle.json, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/diagnosticreport/SpecimenBatteryMapper.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/diagnosticreport/SpecimenBatteryMapperTest.java, gp2gp-translator/src/test/resources/xml/SpecimenBattery/specimen_battery_compound_statement.xml
Update SpecimenBatteryMapper to set issued based on GP Connect requirements.  This should now use the effective time from the `SpecimenBattery`, or then the `DiagnosticReport`, failing that to fallback to `Author.time` from the `ehrComposition`
GP Connect specifies that the issued date on Test Group Header (specimen battery) should use the following to determine its value:
```
The date and time that the result was issued by the laboratory or other report provider.
If this is not provided for a test group header result then it should inherit the date from the DiagnosticReport.
```
It has been reported under NIAD-2911 that it has been identified that the date & time associated with Investigation Results is incorrect.
[mapping-docs]: …
=> NIAD-2911 Fix `Issued` element in SpecimenBatteryMapper to use correct date when populating 

CHANGELOG.md, gp2gp-translator/src/integrationTest/java/uk/nhs/adaptors/pss/translator/EhrExtractHandlingIT.java, gp2gp-translator/src/integrationTest/java/uk/nhs/adaptors/pss/translator/LargeMessagingIT.java, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP10-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP11-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP2-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP3-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP4-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP5-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP6-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP7_vis-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP9-output.json, gp2gp-translator/src/integrationTest/resources/json/LargeMessage/expectedBundleScenario10.json, gp2gp-translator/src/integrationTest/resources/json/LargeMessage/expectedBundleScenario11.json, gp2gp-translator/src/integrationTest/resources/json/LargeMessage/expectedBundleScenario6.json, gp2gp-translator/src/integrationTest/resources/json/expectedBundle.json, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/ObservationMapper.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/ObservationMapperTest.java
Update ObservationMapper to ensure that the availabilityTime is used when available, when mapping ObservationStatements and ObservationRequests.
Add Unit tests to ObservationMapperTest for this updated functionality.
GP Connect specifies that the issued date on ObservationStatement should use the following to determine its value:
`The audit trail timestamp representing when the data was recorded.`
It has been reported under NIAD-2911 that it has been identified that the date & time associated with Investigation Results is incorrect.
=> Update ObservationMapper to ensure AvailabilityTime is used for Issued, when available

developer-information.md
Remove reference to passwords, which don't need populating anymore.
=> Improve the wording of the developer guidance

gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/medication/MedicationRequestPlanMapper.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/medication/MedicationRequestPlanMapperTest.java
Incumbent can also include additional comments after the original reason, let's make sure we remove the duplication in that case too.
=> NIAD-3054: Also ignore discontinuation reason where the originalText is prefix of pertinentInformation

CHANGELOG.md, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP10-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP11-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP2-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP4-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP5-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP6-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP9-output.json, gp2gp-translator/src/integrationTest/resources/json/LargeMessage/expectedBundleScenario6.json, gp2gp-translator/src/integrationTest/resources/json/LargeMessage/expectedBundleScenario7.json, gp2gp-translator/src/integrationTest/resources/json/expectedBundle.json, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/ObservationCommentMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/diagnosticreport/SpecimenBatteryMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/diagnosticreport/SpecimenCompoundsMapper.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/ObservationCommentMapperTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/diagnosticreport/SpecimenBatteryMapperTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/diagnosticreport/SpecimenCompoundsMapperTest.java, gp2gp-translator/src/test/resources/xml/ObservationComment/nullflavour_availability_time.xml, gp2gp-translator/src/test/resources/xml/SpecimenBattery/specimen_battery_compound_statement.xml, gp2gp-translator/src/test/resources/xml/SpecimenComponents/specimen_cluster_compound_statement_availability_time_unk.xml
In NIAD-2991 we were provided with an anonymised GP2GP investigation from production, where the availabilityTime for:
- Test Group Header
- Test Result
- Filing Coment
Were the values which seemed to be the correct value to use for `issued`.
=> NIAD-2991: Use the NarrativeStatement/availabilityTime for filing comment ObservationStatement.issued

gp2gp-translator/build.gradle, gp2gp-translator/src/integrationTest/java/uk/nhs/adaptors/pss/translator/amqp/ServiceFailureIT.java
Test is placed to confirm that DLQ redelivery mechanism is working as expected.
We need to be sure that in case of any exceptional scenario a message will be delivered to DLQ.
=> Niad-3102: test dlq redelivery behaviour

CHANGELOG.md, gpc-api-facade/src/integrationTest/java/uk/nhs/adaptors/pss/gpc/controller/AcknowledgeRecordControllerIT.java, gpc-api-facade/src/main/java/uk/nhs/adaptors/pss/gpc/service/AcknowledgeRecordService.java, gpc-api-facade/src/test/java/uk/nhs/adaptors/pss/gpc/service/AcknowledgeRecordServiceTest.java, gpc-api-facade/src/test/java/uk/nhs/adaptors/pss/gpc/service/PatientTransferServiceTest.java
Previously:
- **Given** a POST request made to the `/$gpc.ack` endpoint.
- **When** a request header is passed for `conversationId` with a lowercase UUIDv4.
- **Then** the response would be status 500 (Internal Server Error).
Now:
- **Given** a POST request made to the `/$gpc.ack` endpoint.
- **When** a request header is passed for `conversationId` with a lowercase OR uppercase UUIDv4.
- **Then** the response would be status 200 (OK).
This bug could cause confusion and questions from NMEs as to why the endpoint doesn’t work.
=>  [NIAD-2988] Lowercase Conversation ID for getMigrationRequest()

gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/config/AmqpConfiguration.java
Spring 6 will complain about this.
=> Fix method name to match bean name

gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/service/AttachmentReferenceUpdaterService.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/service/InboundMessageMergingService.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/task/EhrExtractMessageHandler.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/service/AttachmentReferenceUpdaterServiceTests.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/service/InboundMessageMergingServiceTests.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/task/EhrExtractMessageHandlerTest.java
=> Refactor: Clarify purpose of AttachmentReferenceUpdaterService

gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/config/AmqpConfiguration.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/AgentDirectoryMapper.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/AllergyIntoleranceMapperTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/BloodPressureMapperTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/ObservationMapperTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/medication/MedicationStatementMapperTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/util/AddressUtilTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/util/CompoundStatementUtilTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/util/DegradedCodeableConceptsTests.java, gpc-api-facade/src/main/java/uk/nhs/adaptors/pss/gpc/config/AmqpConfiguration.java, gpc-api-facade/src/main/java/uk/nhs/adaptors/pss/gpc/controller/validation/PatientTransferRequestValidator.java
StringUtils replacement + test classes cleanup
StringUtils class of io.micrometer library has been declared as deprecated, hence it was replaced by another alternative StringUtils implementation
=> Removal of deprecated StringUtils class + test cleanup

gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/DocumentReferenceMapperTest.java
Easier to find test when it's naming matches convention.
Internal change (non-breaking change with no effect on the functionality affecting end users
=> Refactor: Rename test class name to match production code class name

gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/diagnosticreport/DiagnosticReportMapperTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/diagnosticreport/SpecimenBatteryMapperTest.java, gp2gp-translator/src/test/resources/xml/DiagnosticReport/diagnostic_report_with_observation_statements.xml
Additional unit tests were added to make sure that DiagnosticReport ordering works as expected.
There were no tests specifically looking to assess the ordering of DiagnosticReport  results.
=> NIAD-2961: additional tests to confirm diagnostic report ordering

CHANGELOG.md, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP9-output.json, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/diagnosticreport/SpecimenCompoundsMapper.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/diagnosticreport/SpecimenCompoundsMapperTest.java, gp2gp-translator/src/test/resources/xml/SpecimenComponents/specimen_with_three_test_group_headers.xml
Have added an additional test to ensure test group header references are correctly ordered
Updated SpecimenCompoundMapper to cycle through all "BATTERY" and "CLUSTER" in order rather than processing each type seperately.
This ensures that they are added to the diaganostic report results in the correct order.
The PS Adaptor does not preserve the correct order of "Test Group Headers" within a Diagnostic Report.
This can result in the resources being displayed in the incorrect order in the consuming system.
=> NIAD-2961-preserve-test-group-header-ordering

CHANGELOG.md, snomed-database-loader/load_release-postgresql.sh
Password percent-encoding 
Sometimes passwords can include '%' special characters which could result in "psql: error: invalid percent-encoded token...". So in order to mitigate such a situation the password percent-encoding has been introduced by this PR.
=> NIAD-3138: password encoding

CHANGELOG.md, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP9-output.json, gp2gp-translator/src/integrationTest/resources/json/expectedBundle.json, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/diagnosticreport/SpecimenCompoundsMapper.java
A BATTERY CompoundStatement can only have two types of component inside it according to the GP2GP specification. These are:
- A CLUSTER CompoundStatement
- An ObservationStatement
The existing code within handleBatteryCompoundStatement deals with each of those cases already. The additional code removed in this change appears to deal with any type of CompoundStatement. Given that the only CompoundStatement which is valid to appear here is a CLUSTER, and the code for handleClusterCompoundStatement already calls handleObservationStatement, there is no point to this code.
By removing this duplicate call to handleObservationStatement we also fix the issue where Observations are being generated with two identical "category" values of "Laboratory".
Furthermore, this code is completely untested. …
=> NIAD-2851: Remove unexplained call to handleObservationStatement

gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/diagnosticreport/SpecimenCompoundsMapper.java
Code optiomization for two loops in handleBatteryCompoundStatement method
Extracting the partial result of a stream process and processing it further with forEach is less readable than aggregating it all together as part of one processing flow.
=> Small SpecimenCompoundsMapper code refactoring

gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/service/ConfidentialityService.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/medication/MedicationMapperUtilsTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/medication/MedicationRequestOrderMapperTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/medication/MedicationRequestPlanMapperTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/medication/MedicationStatementMapperTest.java
Mostly cleanup the excessive code around isPresent assertion
We don't need more code in tests to achieve the same result
=> Small Code optimizations

README.md
Readme edition
Some phrases can be reworded and some made more concise which looks better and takes less space.
=> README reformat and rewording to make it more concise

CHANGELOG.md, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/ConditionMapper.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/ConditionMapperTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/service/ConfidentialityServiceTest.java, gp2gp-translator/src/test/resources/xml/Condition/linkset_valid_ehr_composition_nopat_confidentiality_code.xml, gp2gp-translator/src/test/resources/xml/Condition/linkset_valid_nopat_confidentiality_code.xml
This PR introduces the capability to handle `confidentialityCodes` for` Conditions`. The implementation checks if a `Linkset` or `EhrComposition` contains a confidentiality code with the value `NOPAT`. If this code is present, meta security is added to the resource; otherwise, the code is ignored.
More details can be found on the [ticket](https://nhse-dsic.atlassian.net/browse/NIAD-3131).
=> [NIAD-3131] Add ConfidentialityCode support for `Conditions`

gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/diagnosticreport/SpecimenMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/service/BundleMapperService.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/diagnosticreport/SpecimenMapperTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/service/BundleMapperServiceTest.java
=> Refactor: Rename mapSpecimen to mapSpecimens

gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/ConditionMapperTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/service/ConfidentialityServiceTest.java
Addressed some points that @adrianclay left on the main PR - https://github.com/NHSDigital/nia-patient-switching-standard-adaptor/pull/735.
=> NIAD-3131-TIDY - Addressed some points made in the NIAD-3131 PR

CHANGELOG.md, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/ImmunizationMapper.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/ImmunizationMapperTest.java, gp2gp-translator/src/test/resources/xml/Immunization/immunization_with_ehrComposition_nopat_confidentiality_code.xml, gp2gp-translator/src/test/resources/xml/Immunization/immunization_with_observation_nopat_confidentiality_code.xml
* Updated ImmunizationMapper to use the confidentiality service when generating the Meta by checking if a `NOPAT` confidentiality code is populated in either the `ehrComposition` or the `ObservationStatement`.
* Create new tests to cover the above scenario.
* Add additional test xml files for the new tests.
When provided with the following `confidentialityCode` element in either the `ehrComposition` or the `ObservationStatement` when mapping immunizations:
```xml
<confidentialityCode
code="NOPAT"
codeSystem="2.16.840.1.113883.4.642.3.47"
displayName="no disclosure to patient, family or caregivers without attending provider's authorization" />
```
The produced immunization will contain the following JSON Element:
```json
{
"meta": {
"security": [{
"system":"http://hl7.org/fhir/v3/ActCode", …
```
=> NIAD-3133: Populate the "no disclosure to patient" label for Immunization

gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/service/ConfidentialityServiceTest.java
There were some holes in the current testsuite
=> Add more tests for ConfidentialityService

CHANGELOG.md, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/BloodPressureMapper.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/BloodPressureMapperTest.java, gp2gp-translator/src/test/resources/xml/BloodPressure/battery_compound_statement_containing_confidentiality_code.xml, gp2gp-translator/src/test/resources/xml/BloodPressure/diastolic_observation_containing_confidentiality_code.xml, gp2gp-translator/src/test/resources/xml/BloodPressure/ehr_composition_containing_confidentiality_code.xml, gp2gp-translator/src/test/resources/xml/BloodPressure/systolic_observation_containing_confidentiality_code.xml
Add `ConfidentialityService` to `BloodPressureMapper`. 
Add functionality to populate the security meta when the provided `ehrComposition` contains a "NOPAT" `confidentialityCode`. 
Add functionality to populate the security meta when the provided `compoundStatement` contains a "NOPAT" `confidentialityCode`. 
Add functionality to populate the security meta when the diastolic or systolic `ObservationStatement` contains a "NOPAT" `confidentialityCode`. 
Add Unit Tests for the above functionality.
Add Unit Test xml files for the above tests.
When provided with the following `confidentialityCode` element in either the `ehrComposition`, `compoundStatement` or within any if the diastolic or systolic `ObservationStatements`
```xml
<confidentialityCode
code="NOPAT" …
```
=> NIAD-2394: Populate the "no disclosure to patient" label for `BloodPressure`

CHANGELOG.md, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP9-output.json, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/diagnosticreport/DiagnosticReportMapper.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/diagnosticreport/DiagnosticReportMapperTest.java
Updated DiagnosticReportMapper to set the effective time and performer values based on those found in `ehrComposition / author`.
Added unit test for this functionality.
Updated test XML file for unit test to reflect change.
* When mapping `filing comments` the resultant `Observation.effectiveDateTime` should be the value found in the source xml `ehrComposition / author / time @[value]`
* When mapping `filing comments` the resultant `Observation.issued` should be the `availabilityTime` value found in the associated `User Comment NarrativeStatement` from which the `filing comment` is built.
* When mapping `filing comments` the resultant `Observation.performer.reference` should contain a practitioner reference to the value found in `ehrComposition / author / agentRef / id @[root]`
Please …
=> NIAD-3146: Incorrect filing date and performer on Filing Comments

CHANGELOG.md, README.md, gpc-api-facade/src/main/java/uk/nhs/adaptors/pss/gpc/config/filter/ConversationIdFilter.java, gpc-api-facade/src/main/java/uk/nhs/adaptors/pss/gpc/config/filter/package-info.java, gpc-api-facade/src/test/java/config/filter/ConversationIdFilterTest.java, gpc-api-facade/src/test/java/uk/nhs/adaptors/pss/gpc/service/PatientTransferServiceTest.java
*Create Unit Tests for ConversationIdFilter
* Add Unit Tests to ensure that `Bad Request` operational outcomes are returned when an invalid `ConversationId` is provided. 
* Add package-info.java to resolve warnings around @NonNullApi 
* Update ConversationIdFilter to return `Bad Request` operational outcomes are returned when an invalid `ConversationId` is provided. 
* Update README.md to document updated response
* Update CHANGELOG.md
Currently the GPC Facade endpoint will accept `ConversationId` headers, where the value is populated but with a value is not a valid UUID. 
When given an invalid argument, or missing argument which is required the adaptor should be returning a 400 Bad Request HTTP Error.
This should provide the `OperationalOutcome` in the content (as specified by GP …
=> NIAD-3145: PS Adaptor should reject request with an invalid `ConversationId` header

CHANGELOG.md
=> Add 3.0.3 to CHANGELOG.md

CHANGELOG.md, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/amqp/MhsDaisyChainingQueueConsumer.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/amqp/MhsQueueConsumer.java
In the event that an MHS inbound message cannot be processed it would be useful to be clear what happens to the message once the error happens.
By outputing this at DEBUG level this message wouldn't have been displayed in a production like environment, making it harder for the NME to know what's happened to the corrupt message.
Bug fix (non-breaking change which fixes an issue)
=> NIAD-2671: Output dead letter message at INFO level

gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/util/AddressUtil.java
Replace obsolete and incorrect `micrometer` implementation of `StringUtils` with the `apache.commons` version.
'micrometer' version of StringUtils is being used which is the incorrect implementation and is now marked as obsolete.
=> Replace obsolete and incorrect `micrometer` implementation of `StringUtil`

gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/AbstractMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/AllergyIntoleranceMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/BloodPressureMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/ConditionMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/DocumentReferenceMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/EncounterMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/ImmunizationMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/LocationMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/ObservationCommentMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/ObservationMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/ProcedureRequestMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/ReferralRequestMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/TemplateMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/diagnosticreport/SpecimenBatteryMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/diagnosticreport/SpecimenCompoundsMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/util/ResourceUtil.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/util/XmlParseUtilService.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/diagnosticreport/SpecimenBatteryMapperTest.java
Replaced misspelling of `practise` to `practice` when used to refer to a medical practice / code in mappers.
The incorrect spelling of  `practise` is used in many places.  When referring to a medical practice / code this spelling should be `practice`.
=> refactor-spelling-error-practise-to-practice

CHANGELOG.md, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP2-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP4-output.json, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/medication/MedicationRequestMapper.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/medication/MedicationRequestMapperTest.java
* Add functionality to ensure that a new `MedicationStatement` is generated when multiple `MedicationRequest[Order]`s share the same acute `MedicationRequest[Plan]`.
* Add functionality to duplicate the existing `MedicationStatement` and copy the contained values using the existing MedicationStatement.copy() method.
* Add functionality to generate and set a new `id` and `identifier` for the generated `MedicationStatement` based on the ID of the associated generated `MedicationRequest[Plan]`.
* Add functionality to update the `basedOn` reference to instead reference the generated `MedicationRequest[Plan]`.
* Add functionality to update `effectivePeriod` to match that of `dispenseRequest.validityPeriod` from the associated `MedicationRequest[Order]`.
* Add functionality to update the value …
=> NIAD-3170: Create duplicate MedicationStatements when multiple Orders reference the same acute Plan

gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP2-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP4-output.json, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/medication/MedicationRequestMapper.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/medication/MedicationRequestMapperTest.java
Add functionality when generating `MedicationRequest[plan]`s so that `validityPeriod` is copied from the original `MedicationRequest[Order]. Add a unit test for this functionality.
Update the integration test output files to reflect these changes.
The original requirements of:
> dispenseRequest.validityPeriod - Is generated by copying same field from over the MedicationRequest[intent=**plan**]
were a mistype and should have read:
>dispenseRequest.validityPeriod - Is generated by copying same field from over the MedicationRequest[intent=**order**]
This change introduces the functionality and tests for this.
=> NIAD-2194: Update `validityPeriod` in generated `Plan`s when multiple `Orders` reference the same acute `Plan`

gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/medication/MedicationRequestMapper.java
* Add Slf4j to `MedicationRequestMapper`
* Add a log message to indicate that a `MedicationRequest(Plan)` has been generated for a particular `MedicationRequest(Order)`.
* Add a log message to indicate that a `MedicationStatement` has been generated for a particular `MedicationRequest(Order)`.
To indicate in the logs when `MedicationRequest(Plan)` or `MedicationStatement` has been generated for a particular `MedicationRequest(Order)` when mapping acute plans.
=> NIAD-2194: Add logging to `MedicationRequestMapper`

gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/medication/MedicationRequestMapperTest.java
Refactor unit tests in `MedicationRequestMapperTests` to use nested classes for the grouped tests for `acute` and `repeat` when two `ehrSupplyPrescribe` reference one `ehrSupplyAuthorise`.
Refactoring to group similar tests into nested test classes for readability and to allow more descriptive test names
=> Refactor unit tests in `MedicationRequestMapperTests` to use nested classes.

gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP2-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP4-output.json, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/medication/MedicationRequestMapper.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/medication/MedicationRequestMapperTest.java
When an accute med has multiple issues, we generate individual plan/statement for each order.
This updates the original statements lastIssueDate to correspond to the date on its corresponding MedicationRequest[order].
Previously the lastIssueDate was the most recent date of all the orders.
Bug fix (non-breaking change which fixes an issue)
=> Update original MedicationStatement lastIssueDate for multiple acute med

gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/medication/MedicationRequestMapper.java
* Fix issue with incorrect ID being output when logging that a `medicationStatement` has been generated during `MedicationRequest` mapping
Recently introduced logging to notify that a `MedicationStatement` had been generated during the mapping process (when multiple `Order`s reference the same acute `Plan`) included the id of the generated `Plan` not the generated `MedicationStatement` as expected.
=> Logging: Incorrect ID output when generating `MedicationStatements`

gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP2-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP4-output.json, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/medication/MedicationRequestMapper.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/medication/MedicationRequestMapperTest.java
* Add unit tests to ensure that the generated `MedicationStatement` has an `effective.end` set to the value of `effective.start` when the status is `active` and associated `Order` has no `dispenseRequest.validityPeriod.end`.
* Add unit tests to assert the current behaviour depending on the `MedicationStatement.status`
* Add functionality to `MedicationRequestMapper` for the above.
* Update integration test files to now test that the `end` value is correctly populated.
Currently we only set `effective.start` value when generating a `MedicationStatement` whilst mapping an acute `plan` where multiple `ehrSupplyPrescribe` reference a single acute `ehrSupplyAuthorise`, whilst when building new `MedicationStatements` we also set `end` to the same value as `start` when `status` is `active` and …
=> NIAD-3170: Set effective end date to start date in generated `MedicationStatement` when status is `active` when mapping acute plans.

gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/medication/MedicationMapperUtils.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/medication/MedicationMapperUtilsTest.java
* Added public method `isAcutePrescription` to check if the provided `ehrSupplyPrescribe` has a `repeatNumber` with a value of `0`.
* Added unit tests for the above.
So that this check can be consumed in the `MedicationRequestMapper` without needing to duplicate code.
=> Expose check for if `ehrSupplyAuthorise` is an acute prescription

README.md, getting-started-instructions.md
The process of configuring the Requesting/Sending adaptors is quite involved.
Having a step-by-step set of instructions should help reduce the amount of support queries required.
=> Create getting started documentation

CHANGELOG.md, OPERATING.md, dependent-service-downtime-and-ps-adaptor-behavior.md
A guidance was added that highlights the specific focus on the dependent services and how the PS Adaptor operates when those services are unavailable
This guide outlines the expected behavior of the PS Adaptor when various dependent services are down. 
The PS Adaptor works in conjunction with several services including the GP2GP Translator, MHS Adaptor, Facade, and others. 
The guide explains the effects of outages and how the system behaves in each case that might be very helpful while investigating different issues related to the PS Adaptor.
=> Niad-2913: Guidance around what happens with PS Adaptor in failure modes

dependent-service-downtime-and-ps-adaptor-behavior.md
Line alignments to follow the same pattern
Some lines were not following the same visual pattern
=> NIAD-2913: Line alignments to follow the same pattern

gp2gp-translator/build.gradle, gp2gp-translator/src/integrationTest/java/uk/nhs/adaptors/pss/translator/service/BundleMapperServiceIT.java, gp2gp-translator/src/integrationTest/resources/xml/mapping/ehr-extract/ehr-document-and-no-organisations.xml, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/DuplicateObservationStatementMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/service/BundleMapperService.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/DuplicateObservationStatementMapperTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/service/BundleMapperServiceTest.java
Remove duplicate Observations with the same codeable concepts
This PR provides the removal of duplicate observations with the same codeable concepts that cause double entries in the final JSON output rendered by the PS Adaptor.
=> NIAD-3187: Deduplicate Observations where the CodableConcept is identical to another within the same EhrExtract and contains no additional information

CHANGELOG.md, common/src/main/java/uk/nhs/adaptors/common/config/ObjectMapperConfig.java, gp2gp-translator/src/integrationTest/java/uk/nhs/adaptors/pss/translator/service/AcknowledgeRecordServiceIT.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/service/AcknowledgeRecordService.java, gpc-api-facade/src/main/java/uk/nhs/adaptors/pss/gpc/config/ApplicationConfiguration.java
Removal of the limit of string size that can be processed by Jackson ObjectMapper
ObjectMapper underneath uses Jackson which has a limit of 20 Mb of data that it can process. The data that PS Adaptor is working with can be much bigger in size than the limit hence we need to remove this limit and allow the adaptor to handle much bigger documents.
=> NIAD-3236: removing the limit of string size that can be processed by ObjectMaper

gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/service/AcknowledgeRecordService.java
Logger message fix
When original message can't be parsed it is good to trigger a logger and include the full exception message about the root cause of an issue.
=> NIAD-3236: logger message fix to include the full exception message

gpc-api-facade/src/integrationTest/java/uk/nhs/adaptors/pss/gpc/controller/PatientTransferControllerIT.java
Running every test scenario in a separate transaction 
Running every test scenario in a separate transaction makes them independent which each other and doesn't leave a trace in a database that affects other scenarios
=> Running every test scenario in a separate transaction to make the tests more independent and predictable

gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/AgentDirectoryMapperTest.java
Fix warnings for `raw use of parameterized class 'List'` which is the mirror of the javac rawtypes warning. Although this is valid in java, it allows any object to be inserted into the list, regardless of its assigned type.
Where the raw use of `List` was used in the file AgentDirectoryMapperTest it was suitable to use `var` rather than `List<? extends DomainResource`.
The following warning is reported:
**Raw use of parameterized class 'List'** 
Inspection info: _Reports generic classes with omitted type parameters. Such raw use of generic types is valid in Java, but it defeats the purpose of type parameters and may mask bugs. This inspection mirrors the rawtypes warning of javac._
Examples:
```java
//warning: Raw use of parameterized class 'List'
List list = new ArrayList<String>(); …
```
=> Fix warnings for `raw use of parameterized class 'List'` in AgentDirectoryMapperTest

CHANGELOG.md, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/AgentDirectoryMapper.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/AgentDirectoryMapperTest.java
Fixed a bug where if the name element was omitted for an `agentPerson` (which is a valid use case) then an exception would be thrown.  Instead, this now produces a `Practitioner` with a family name of `"unknown"` as documented.
Added Unit Test for the above functionality.
When an `Agent` is provided in the XML with a `agentPerson` element but without a nested `name` element: 
```xml
<Agent classCode="AGNT">
<id root="6C8AC7E0-4D90-10C5-5FD3-F2C05C658E18" />
<code code="125676002" codeSystem="2.16.840.1.113883.2.1.3.2.4.15" displayName="Person">
<originalText>Other</originalText>
</code>
<agentPerson classCode="PSN" determinerCode="INSTANCE" />
</Agent>
```
Then the adaptor currently throws a BundleMappingException.  It is expected instead that this is handled gracefully, with produced …
=> Fix bug where if the name element was omitted for an `agentPerson` then an exception would be thrown

CHANGELOG.md, developer-information.md
=> Add 3.0.7 to CHANGELOG.md

gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/util/ResourceFilterUtil.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/util/ResourceFilterUtilTest.java, gp2gp-translator/src/test/resources/xml/ResourceFilter/ehr_extract_with_referral_request_to_external_document_linkset.xml
* Add Test to check verify that the provided `LinkSet` is a "Referral Request to External Document LinkSet."
* Add test XML file containing a "Referral Request to External Document LinkSet."
* Add method `isReferralRequestToExternalDocumentLinkSet` to `ResourceFilterUtil` with parameters for the `EhrExtract` and the `LinkSet` itself to identify `LinkSets` matching the criteria for a "Referral Request to External Document LinkSet."
As part of the implementation for NIAD-3220, it is necessary to identify `LinkSets` which are a "Referral Request to External Document LinkSet" in order to be able to then use this for filtering in the `ConditionMapper` to exclude the `Condition` from being mapped, and in `ReferralRequest` mapper to identify any of these LinkSets when populating the …
=> NIAD-3220: Add Resource filter to identify "ReferralRequest to ExternalDocument LinkSets"

CHANGELOG.md, OPERATING.md, README.md
=> Rename adaptor from patient switching to GP2GP FHIR Request Adaptor

.github/workflows/build.yml
Make the buildId comment only run on PR, not when merging to main
The buildId comment attempts to create a comment on the PR when merging to main.  This step should only run against the PR or it will report an error
=> Make BuildId comment job only run on pull request

.github/workflows/mutation-tests.yml
Add an if condition to the mutation testing GitHub action to prevent the mutation testing from being run if the GitHub actor is dependabot.
Currently the mutation testing workflow triggers when dependabot raises a PR.  This fails as Dependabot does not have access to GitHub secrets
=> Prevent Dependabot running mutation testing

.github/workflows/build.yml
Ensure that the comment showing the build ID is updated and a new one is not created when a PR is rebuilt
Each time a PR was re-run, then a new build ID comment was posted.  If the comment exists it should be amended with the latest successful build ID instead
=> Fix issue with duplicate Build ID comments

.github/workflows/test.yml
Added checkstylentegrationTests and spotbugsIntegrationTests to github `Test` action
Checkstyle and SpotBugs were not running against the integration tests.
=> Run checkstyle and spotbugs against IntegrationTest in github actions

getting-started-instructions.md
Has been a source of confusion/pain for the NMEs when setting up the adaptor.
Documentation
=> Add DNS resolution information to getting-started-information.md

gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/model/NACKReason.java
Add `responseText` to enum `NACKReason` to be used when populating the NACK response.
As we now require the displayName to populated when providing a NACK response, we need to be able to provide responseText along with the code.  These values were populated from the details provided in the "NPFIT-PC-BLD-0083 GP2GP Response Codes" PDF.
- [] I have updated the [Changelog](/CHANGELOG.md) with details of my change in the UNRELEASED section if this change will affect end users
=> Add `responseText` to enum `NACKReason` to be used when populating the NACK response

gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/model/NACKMessageData.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/service/ApplicationAcknowledgementMessageService.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/service/NackAckPreparationService.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/task/COPCMessageHandler.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/task/scheduled/EHRTimeoutHandler.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/service/ApplicationAcknowledgementMessageServiceTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/service/NackAckPreparationServiceTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/task/COPCMessageHandlerTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/task/SendNACKMessageHandlerTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/task/scheduled/EHRTimeoutHandlerTest.java
Will allow us to get both the code and the textual "Response text" from the enum when generating the XML.
=> Refactor: Replace NACKMessageData.nackCode String with NACKReason enum

gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/service/NackAckPreparationServiceTest.java
* Refactor `NackAckPreparationsServiceTest` to reduce duplicated code and consolidate into parameterised tests where suitable.
There were a lot of test each testing permutations of an `enum` for both the RCMR and COPC set of tests. These were unnecessary and could be consolidated into parameterised tests.
=> Refactor `NackAckPreparationsServiceTest` to reduce code duplication

CHANGELOG.md, gp2gp-translator/src/integrationTest/java/uk/nhs/adaptors/pss/translator/FailedProcessHandingIT.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/service/ApplicationAcknowledgementMessageService.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/util/template/parameter/ApplicationAcknowledgmentParams.java, gp2gp-translator/src/main/resources/templates/applicationAcknowledgementTemplate.mustache, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/service/ApplicationAcknowledgementMessageServiceTest.java
It appears that other GP2GP implementations send the NACK response text as part of the coded response.
This change brings us in line with these.
Furthermore, one implementation claims that they require this field to be populated otherwise they will error.
Bug fix (non-breaking change which fixes an issue)
=> NIAD-3260: When sending a NACK to the sending system, also include the responseText

gp2gp-translator/src/integrationTest/java/uk/nhs/adaptors/pss/translator/amqp/ServiceFailureIT.java
It appears that the SpyBeans are causing issues between tests. One spy can interfere with a subsequent test.
Clearing the ApplicationContext between each test seems to fix this.
Downside of this is that the tests are a bit slower, but given that the tests already take 5 minutes that isn't a noticable change.
=> Clear ApplicationContext before each ServiceFailureIT test

CHANGELOG.md, gp2gp-translator/src/integrationTest/java/uk/nhs/adaptors/pss/translator/EhrExtractHandlingIT.java, gp2gp-translator/src/integrationTest/java/uk/nhs/adaptors/pss/translator/FailedProcessHandlingIT.java, gp2gp-translator/src/integrationTest/java/uk/nhs/adaptors/pss/util/BaseEhrHandler.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/service/FailedProcessHandlingService.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/task/EhrExtractMessageHandler.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/service/FailedProcessHandlingServiceTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/task/EhrExtractMessageHandlerTest.java
The GP2GP spec allows for an EHR Extract to be resent in the event of a failure.
This can be useful if there were temporary technical issues which caused the failure.
New feature (non-breaking change which adds functionality)
=> Accept a "resent" EHR Extract from an incumbent as per the spec

gpc-api-facade/src/main/java/uk/nhs/adaptors/pss/gpc/controller/handler/OperationOutcomeExceptionHandler.java
Since upgrading to Spring Framework 6.2, this method has been deprecated, and it's now producing a warning within the logs.
Use replacement method instead
=> Remove call to deprecated HttpHeaders.writableHttpHeaders method

CHANGELOG.md, gp2gp-translator/src/integrationTest/resources/json/expectedBundle.json, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/EncounterMapper.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/EncounterMapperTest.java
Conditions are mapped into relatedProblemHeader
When mapping an ehrComposition which contains a “flat” structure, i.e. no Topic, when the [GP Connect Topic List](https://developer.nhs.uk/apis/gpconnect-1-6-0/accessrecord_structured_development_list_consultation.html#list-topic) is generated then the “relatedProblemHeader” extension is populated.
=> NIAD-3001: Conditions are mapped into relatedProblemHeader

gp2gp-translator/src/integrationTest/java/uk/nhs/adaptors/pss/translator/E2EMappingIT.java, gp2gp-translator/src/integrationTest/java/uk/nhs/adaptors/pss/translator/EhrExtractHandlingIT.java, gp2gp-translator/src/integrationTest/java/uk/nhs/adaptors/pss/translator/service/AcknowledgeRecordServiceIT.java, gp2gp-translator/src/integrationTest/java/uk/nhs/adaptors/pss/translator/task/scheduled/EHRTimeoutHandlerIT.java
=> Replace all usages of deprecated MockBean with MockitoBean

schema/build.gradle
* Use `junit-bom` to ensure package compatibility.
* Update commons-lang3 to resolve vulnerability.
Using `junit-bom` ensure that any junit dependencies versions are managed by the BOM and prevents dependabot from failing when it tries to update one junit dependency but not the other.
=> Fix jupiter dependencies and vulnerability
