NHSDigital/integration-adaptor-gp2gp-requesting

gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/ConditionMapper.java
-> According to schema - minOccurs="0" maxOccurs="1"
=> NIAD-2046: Secure ConditionMapper from nulls

gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/ConditionMapper.java
Changed logic of onset field generating
=> NIAD-2046: Change conditions of ONSET generating

gp2gp-translator/src/integrationTest/resources/json/expectedBundle.json, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/ObservationCommentMapper.java
- implemented compound statement extractor in observation comment
=> NIAD-2047 implemented missing extractor

gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/ObservationCommentMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/ObservationMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/util/EhrResourceExtractorUtil.java
=> NIAD-2057 Fixed potential NPE caused by null Performer

gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/util/ObservationUtil.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/util/ObservationUtilTest.java, gp2gp-translator/src/test/resources/xml/Observation/decimal_reference_range_observation_example.xml
Bugfix to handle decimal string values in referenceRange elements
=> NIAD-2090: NumberFormatException when mapping Observation with decimal referenceInterpretationRange value

gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/exception/BundleMappingException.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/service/BundleMapperService.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/task/EhrExtractMessageHandler.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/task/MhsQueueMessageHandler.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/service/BundleMapperServiceTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/task/EhrExtractMessageHandlerTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/task/MhsQueueMessageHandlerTest.java
Trigger NACK message when there are bundle mapping failures.
=> NIAD-2109 mapping errors do not trigger NACK message BUG FIX

config/spotbugs/exclude.xml, db-connector/changelog/migration/09-create-patient_attachment_log-table.xml, db-connector/src/main/java/uk/nhs/adaptors/connector/config/DbConnectorConfiguration.java, db-connector/src/main/java/uk/nhs/adaptors/connector/dao/PatientAttachmentLogDao.java, db-connector/src/main/java/uk/nhs/adaptors/connector/mapper/PatientAttachmentLogRowMapper.java, db-connector/src/main/java/uk/nhs/adaptors/connector/model/PatientAttachmentLog.java, db-connector/src/main/java/uk/nhs/adaptors/connector/service/PatientAttachmentLogService.java, db-connector/src/main/resources/uk/nhs/adaptors/connector/dao/PatientAttachmentLogDao/delete_patient_attachment_log.sql, db-connector/src/main/resources/uk/nhs/adaptors/connector/dao/PatientAttachmentLogDao/insert_patient_attachment_log.sql, db-connector/src/main/resources/uk/nhs/adaptors/connector/dao/PatientAttachmentLogDao/select_patient_attachment_log.sql, db-connector/src/main/resources/uk/nhs/adaptors/connector/dao/PatientAttachmentLogDao/update_patient_attachment_log.sql, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/task/EhrExtractMessageHandlerTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/task/MhsQueueMessageHandlerTest.java
Feature complete for patient attachment log migration
=> Niad 2104 patient attachment migration

db-connector/src/main/java/uk/nhs/adaptors/connector/dao/PatientAttachmentLogDao.java, db-connector/src/main/java/uk/nhs/adaptors/connector/service/PatientAttachmentLogService.java, db-connector/src/main/resources/uk/nhs/adaptors/connector/dao/PatientAttachmentLogDao/count_attachments_for_migration_id.sql, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/task/scheduled/EHRTimeoutHandler.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/util/OutboundMessageUtil.java, gp2gp-translator/src/main/resources/application.yml
Handle large message timeouts. 
Refactor EHR timeout handler to be more concise.
=> Handle large message timeouts 

gp2gp-translator/src/integrationTest/java/uk/nhs/adaptors/pss/translator/task/scheduled/EHRTimeoutHandlerIT.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/task/scheduled/EHRTimeoutHandler.java, gp2gp-translator/src/main/resources/application.yml
Add integration tests for timeout
=> Timeout integration tests

gp2gp-translator/src/main/resources/application.yml
The current CRON schedule should be every six hours, but is currently every second of the hour, every six hours.
=> NIAD-2155: Update default CRON schedule - BUG FIX

gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/exception/SkeletonEhrProcessingException.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/service/InboundMessageMergingService.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/task/MhsQueueMessageHandler.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/service/InboundMessageMergingServiceTests.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/task/COPCMessageHandlerTest.java
When a skeleton message is replaced by the complete EHR Extract the additional Narrative Statement is not inserted into the skeleton correctly.
=> NIAD-2154: insert narrative statement into skeleton - BUG FIX

gp2gp-translator/src/nonFunctionalTest/TestPlans/PS_NF_REL_1/PS_NF_REL_1.jmx, gp2gp-translator/src/nonFunctionalTest/TestPlans/PS_NF_REL_1/run-tests.sh, gp2gp-translator/src/nonFunctionalTest/TestPlans/PS_NF_REL_2/run-tests.sh, gp2gp-translator/src/nonFunctionalTest/TestPlans/PS_NF_STR_1/PS_NF_STR_1.jmx, gp2gp-translator/src/nonFunctionalTest/TestPlans/PS_NF_STR_1/README.md, gp2gp-translator/src/nonFunctionalTest/TestPlans/PS_NF_STR_1/config.properties, gp2gp-translator/src/nonFunctionalTest/TestPlans/PS_NF_STR_1/run-tests.sh, gp2gp-translator/src/nonFunctionalTest/TestPlans/PS_NF_STR_2/PS_NF_STR_2.jmx, gp2gp-translator/src/nonFunctionalTest/TestPlans/PS_NF_STR_2/README.md, gp2gp-translator/src/nonFunctionalTest/TestPlans/PS_NF_STR_2/config.properties, gp2gp-translator/src/nonFunctionalTest/TestPlans/PS_NF_STR_2/run-tests.sh, gp2gp-translator/src/nonFunctionalTest/TestPlans/PS_NF_STR_3/PS_NF_STR_3.jmx, gp2gp-translator/src/nonFunctionalTest/TestPlans/PS_NF_STR_3/README.md, gp2gp-translator/src/nonFunctionalTest/TestPlans/PS_NF_STR_3/build-test-environment.sh, gp2gp-translator/src/nonFunctionalTest/TestPlans/PS_NF_STR_3/config.properties, gp2gp-translator/src/nonFunctionalTest/TestPlans/PS_NF_STR_3/docker-compose.yml, gp2gp-translator/src/nonFunctionalTest/TestPlans/PS_NF_STR_3/run-tests.sh, gp2gp-translator/src/nonFunctionalTest/setup-jmeter.sh
Created fully parameterised tests plan for PS_NF_STR_1 along with execution scripts and running instructions
Created fully parameterised tests plan for PS_NF_STR_2 along with execution scripts and running instructions
Created fully parameterised tests plan for PS_NF_STR_3 along with execution scripts and running instructions
For PS_NF_STR_3, an additional setup script has been created to deploy 2 extra instances of GP2GP Translator for running the test.
=> PS Adaptor - Non Functional Testing PS_NF_STR_1 to 3

gp2gp-translator/src/integrationTest/java/uk/nhs/adaptors/pss/translator/E2EMappingIT.java, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP10-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP11-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP2-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP3-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP4-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP7_vis-output.json, gp2gp-translator/src/integrationTest/resources/json/LargeMessage/expectedBundleScenario10.json, gp2gp-translator/src/integrationTest/resources/json/LargeMessage/expectedBundleScenario11.json, gp2gp-translator/src/integrationTest/resources/json/expectedBundle.json, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/medication/MedicationRequestMapper.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/medication/MedicationRequestMapperTest.java, gp2gp-translator/src/test/resources/xml/MedicationStatement/ehrExtract_AvailabilityTimeNotInMedicationStatement.xml, gp2gp-translator/src/test/resources/xml/MedicationStatement/ehrExtract_AvailabilityTimeNotInMedicationStatementOrEhrComposition.xml, gp2gp-translator/src/test/resources/xml/MedicationStatement/ehrExtract_AvailabilityTimeSetInMedicationStatement.xml
As the title suggests ProcedureRequest MedicationRequest authoredOnDate field is incorrect on all counts. It should be pulled from availabilityTime.
=> NIAD-2622 - PS Adaptor - (Problems Dataset) authoredOnDate should be set by availability Time

docker/release-scripts/ps-mhs-e2e/snowmed-database-loader/load_release-postgresql.sh, snomed-database-loader/load_release-postgresql.sh, test-suite/docker/snomed-database-loader/load_release-postgresql.sh
Loader script fails when using SNOMED Monolith Edition.
=> Niad-2649: support snomed monolith edition

gp2gp-translator/src/integrationTest/resources/json/expectedBundle.json, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/ConditionMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/medication/MedicationMapperUtils.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/ConditionMapperTest.java, gp2gp-translator/src/test/resources/xml/Condition/linkset_medication_refs.xml
Map Medication Request references to the condition extensions array. The ID of the Medication request is determined by the mood code of the GP2GP Medication Statement. Which can be ORD or INT 
ORD ->  id of `EhrSupplyPrescribe` 
INT -> id of `EHRSupplyAuthorise`
=> NIAD-2616: condition missing medication references

README.md
Update readme with instructions for database upgrade
=> NIAD-2677: Update readme with details to update monolith SNOMED Db

README.md, getting-started-with-windows.md
Move windows setup to separate file and update instructions.
=> NIAD-2720-readme-windows-setup-updates

test-suite/README.md
authored by [HarveySembhyNHS](https://github.com/HarveySembhyNHS)
=> add README.md for test-suite

test-suite/README.md
=> Niad-2721: update readme for postman tests

OPERATING.md, README.md, developer-information.md
Add template for operating doc and refactor main readme.
=> NIAD-2766: add operating doc

gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/CodeableConceptMapperTest.java, gp2gp-translator/src/test/resources/xml/CD/concept-id-display-name-no-original-text-example.xml, gp2gp-translator/src/test/resources/xml/CD/concept-id-display-name-original-text-example.xml, gp2gp-translator/src/test/resources/xml/CD/concept-id-no-display-code-example.xml, gp2gp-translator/src/test/resources/xml/CD/description-id-example.xml, gp2gp-translator/src/test/resources/xml/CD/description-id-no-original-text-example-1.xml, gp2gp-translator/src/test/resources/xml/CD/description-id-no-original-text-example-2.xml, gp2gp-translator/src/test/resources/xml/CD/no_snomed_code_with_original_text_example.xml, gp2gp-translator/src/test/resources/xml/CD/no_snomed_code_without_original_text_example.xml, gp2gp-translator/src/test/resources/xml/CD/snomed_code_in_translation_with_display_name_and_original_text_example.xml, gp2gp-translator/src/test/resources/xml/CD/snomed_code_in_translation_with_display_name_example.xml, gp2gp-translator/src/test/resources/xml/CD/snomed_code_in_translation_without_display_name_example.xml, gp2gp-translator/src/test/resources/xml/CD/snomed_code_with_original_text_example.xml, gp2gp-translator/src/test/resources/xml/CD/snomed_code_without_original_text_example.xml, gp2gp-translator/src/test/resources/xml/CD/translation-concept-id-display-in-main-code-no-original-text-example.xml, gp2gp-translator/src/test/resources/xml/CD/translation-concept-id-no-display-code-example.xml, gp2gp-translator/src/test/resources/xml/CD/translation-concept-id-no-display-code-no-original-text-example.xml, gp2gp-translator/src/test/resources/xml/CD/translation-description-id-no-display-code-no-original-text.xml
Inline XML for tests and sort out line lengths
Remove now not required XML files
=> Refactor CodeableConceptMapperTest for readability and consistency

CHANGELOG.md, gp2gp-translator/src/main/resources/templates/applicationAcknowledgementTemplate.mustache
Update ACK template with correct namespaces and class codes. 
The final Ack is not accepted by TPP
- [-] I have made corresponding changes to the documentation
- [-] I have added tests that prove my fix is effective or that my feature works
=> NIAD-2866: Bug Fix - Final ACK not accepted by TPP

CHANGELOG.md
Adding a change log entry for NIAD-2873
Log entry has been added for NIAD-2873.
- [x ] Internal change (non-breaking change with no effect on the functionality affecting end users)
- [x ] I have performed a self-review of my code
=> NIAD-2873: change log entry

CHANGELOG.md, release-scripts/release.sh
=> Update changelog to match 0.14

gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/util/ResourceFilterUtil.java
Refactor duplication
I sense deviation of behaviour will happen if we don't reduce duplication.
=> Refactor: Reduce duplicate code by having ResourceFilterUtil delegate

.github/pull_request_template.md, Jenkinsfile
A couple of unrelated changes, but both small so bundled them.
See commit messages for more details of each change.
=> PR template improvement + Add jenkins timeout

CHANGELOG.md, developer-information.md, release-scripts/release.sh
=> Generate release 0.15

CHANGELOG.md, release-scripts/release.sh
=> Release version 1.0.0

OPERATING.md
Clarify "maintenance window" in SNOMED update process
Maintenance window wasn't clear, so be explicit about what needs to be stopped, and the impact of that.
=> Clarify "maintenance window" in SNOMED update process

gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/config/AmqpConfiguration.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/ConditionMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/ObservationCommentMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/TemplateMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/diagnosticreport/SpecimenMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/medication/MedicationMapperUtils.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/medication/MedicationRequestPlanMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/storage/StorageManagerService.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/task/COPCMessageHandler.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/util/CompoundStatementResourceExtractors.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/util/DegradedCodeableConcepts.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/util/ObservationUtil.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/util/XmlUnmarshallUtil.java, gpc-api-facade/src/main/java/uk/nhs/adaptors/pss/gpc/controller/handler/FhirMediaTypes.java, gpc-api-facade/src/main/java/uk/nhs/adaptors/pss/gpc/controller/header/HttpHeaders.java
Constant code refactoring and improvement
There have been some code refactoring and optimization made to make code more maintainable.
Duplication creates a bigger burden to maintainability and also it creates a higher risk of introducing a bug.
=> Small refactoring to improve code quality, readability and maintainability

CHANGELOG.md
=> Clarify additional upgrade insturctions in CHANGELOG

CHANGELOG.md, release-scripts/release.sh
Changelog and release script
- Updated changelog and release script to match with version 1.2.0
=> Updated CHANGELOG.md and release.sh to latest version of adaptor

CHANGELOG.md, release-scripts/release.sh
=> Release 1.2.1

test-suite/mock-spine-mhs-outbound/src/main/java/uk/nhs/adaptors/gp2gpmhstestenv/mockspinemhsoutbound/service/PatientMigrationRequestService.java
Fix failing postman tests
The postman tests have not been maintained. 
=> NIAD-2916: Postman test fixes

CHANGELOG.md
=> Update changelog to 1.3.0

OPERATING.md
Some resource allocation recommendation added to OPERATING.md doc
Some guidance is useful to know which component needs which amount of resources
=> NIAD-2967: translator resources specification

.github/dependabot.yml
Set up Dependabot for Gradle
Dependabot will help keep dependencies up to date
=> Set up Dependabot for Gradle

CHANGELOG.md
=> updated changelog to 1.4.0

gp2gp-translator/src/integrationTest/resources/json/expectedBundle.json, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/ImmunizationMapper.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/ImmunizationMapperTest.java
Practitioner's role section has been wrapped up into Codeable concept structure
Practitioner's role section in Immunization section has been adjusted to follow the official GP Connect API guidance https://developer.nhs.uk/apis/gpconnect-1-6-0/accessrecord_structured_development_fhir_examples_immunizations.html
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
=> NIAD-3021: coding practitioner role as per GP Connect specification

CHANGELOG.md, release-scripts/release.sh
=> Update changelog to 1.4.2

release-scripts/release.sh
=> Update build tag to 1.4.3

OPERATING.md
=> Clarify a couple of environment variable descriptions

README.md
=> Fix formatting of polling responses

.github/dependabot.yml
=> Add GitHub Actions to Dependabot upgrades

common/build.gradle
=> Remove spring versions as version is managed by spring boot gradle plugin

db-connector/build.gradle, gp2gp-translator/build.gradle
=> Update jdbi3 packages to latest version

common/build.gradle
This should resolve 1 Critical, and 1 High severity CVE
=> Upgrade HAPI FHIR to fix CVEs

gp2gp-translator/src/integrationTest/java/uk/nhs/adaptors/pss/translator/EhrExtractHandlingIT.java, gp2gp-translator/src/integrationTest/java/uk/nhs/adaptors/pss/util/BaseEhrHandler.java, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP10-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP11-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP2-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP3-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP4-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP5-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP6-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP7_vis-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP9-output.json, gp2gp-translator/src/integrationTest/resources/json/LargeMessage/expectedBundleScenario1.json, gp2gp-translator/src/integrationTest/resources/json/LargeMessage/expectedBundleScenario10.json, gp2gp-translator/src/integrationTest/resources/json/LargeMessage/expectedBundleScenario11.json, gp2gp-translator/src/integrationTest/resources/json/LargeMessage/expectedBundleScenario2.json, gp2gp-translator/src/integrationTest/resources/json/LargeMessage/expectedBundleScenario3.json, gp2gp-translator/src/integrationTest/resources/json/LargeMessage/expectedBundleScenario4.json, gp2gp-translator/src/integrationTest/resources/json/LargeMessage/expectedBundleScenario5.json, gp2gp-translator/src/integrationTest/resources/json/LargeMessage/expectedBundleScenario6.json, gp2gp-translator/src/integrationTest/resources/json/LargeMessage/expectedBundleScenario7.json, gp2gp-translator/src/integrationTest/resources/json/LargeMessage/expectedBundleScenario8.json, gp2gp-translator/src/integrationTest/resources/json/LargeMessage/expectedBundleScenario9.json, gp2gp-translator/src/integrationTest/resources/json/expectedBundle.json, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/medication/MedicationMapperContext.java
=> Make integration test snapshot IDs deterministic

CHANGELOG.md
=> update changelog for 2.0.0 release

CHANGELOG.md
=> Niad 2666 mo

gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/AllergyIntoleranceMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/BloodPressureMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/ObservationCommentMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/ObservationMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/diagnosticreport/DiagnosticReportMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/diagnosticreport/SpecimenMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/service/BundleMapperService.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/BloodPressureMapperTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/CodeableConceptMapperTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/ConsultationListMapperTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/EncounterMapperTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/ObservationCommentMapperTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/ReferralRequestMapperTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/UnknownPractitionerHandlerTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/diagnosticreport/SpecimenBatteryMapperTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/diagnosticreport/SpecimenCompoundsMapperTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/diagnosticreport/SpecimenMapperTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/medication/MedicationMapperUtilsTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/medication/MedicationRequestMapperTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/medication/MedicationRequestOrderMapperTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/medication/MedicationRequestPlanMapperTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/medication/MedicationStatementMapperTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/util/AddressUtilTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/util/ResourceReferenceUtilTest.java, schema/src/main/java/org/hl7/v3/RCMRMT030101UK04SpecimenRole.java
Small code optimizations
Small code optimizations to keep the code concise and clean
=> Small code optimizations

gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/TemplateMapper.java
Also clarify a couple of variable names
=> Refactor: Remove unused parameter

CHANGELOG.md
Updated CHANGELOG.md to reflect changes for patch release 2.1.1
=> [NIAD-3045-CHANGELOG] Update CHANGELOG.md for patch release 2.1.1

gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/medication/MedicationRequestPlanMapper.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/medication/MedicationRequestPlanMapperTest.java
=> NIAD-3116: Refactor MedicationRequestPlanMapper code and tests

OPERATING.md, README.md
- Link off to the NME Requirements documentation
- Link off to an example adaptor generated Bundle
- Improve formatting
- Explicit listing of the system dependencies the adaptor has
=> Add some small details to the documentation

.github/dependabot.yml
=> Add `schema` project to Dependabot

docker/gp2gp-translator/Dockerfile, docker/gpc-facade/Dockerfile
=> [NIAD-3119-DOCKER-FIX] Address incorrect PropertiesLauncher namespace

developer-information.md, docker/common-modules/Dockerfile, docker/db-migration/Dockerfile, docker/gp2gp-translator/Dockerfile, docker/gpc-facade/Dockerfile, getting-started-with-windows.md, test-suite/docker/activemq/Dockerfile, test-suite/docker/mock-spine-mhs-outbound/DockerFile
Gives us a couple of years of Long Term Support, and some new features in Java.
=> Upgrade to Java 21

gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/ConditionMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/EncounterMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/ImmunizationMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/ObservationMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/ReferralRequestMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/diagnosticreport/SpecimenCompoundsMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/diagnosticreport/SpecimenMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/medication/MedicationRequestOrderMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/medication/MedicationRequestPlanMapper.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/mapper/medication/MedicationStatementMapper.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/ConditionMapperTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/DocumentReferenceMapperTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/service/ConfidentialityServiceTest.java
Refactoring mapper methods
Mapping methods in mapper classes aggregate too much code which make them bigger than they need to be.
=> Post NIAD-3114 refactoring: Mappers refactoring for more readability

OPERATING.md, README.md
Resource allocation for PS adaptor
Users of PS Adaptor should have some basic guidance about what resources (CPU and memory) should be allocated to PS adaptor for good and solid performance.
=> NIAD-2909: resource allocation recommendation

.gitignore, developer-information.md, gp2gp-translator/build.gradle, gp2gp-translator/src/transformXmlToJson/java/uk/nhs/adaptors/pss/translator/TransformXmlToJsonApplication.java, gp2gp-translator/src/transformXmlToJson/resources/application.yml
This will make testing what the adaptor does with arbitary pieces of XML easier.
=> Add gradle task to convert GP2GP XML to JSON using the translator

CHANGELOG.md
=> Add 3.0.5 to CHANGELOG.md

CHANGELOG.md
=> Add 3.0.6 to CHANGELOG.md

getting-started-instructions.md
Question raised in support mailbox about where to get value from.
=> Document `MHS_SECRET_CA_CERTS` in getting-started-instructions.md

gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/ReferralRequestMapperTest.java
Remove superfluous size assert.
Refactor tests to use extracting() better and make it more readable.
Code Quality cleanup.
=> Refactor of `ReferralRequestMapperTest`

README.md
=> Fix link to API Catalogue

.github/dependabot.yml
This simplifies the configuration
=> Combine all Dependabot gradle upgrades into one schedule

gp2gp-translator/src/integrationTest/java/uk/nhs/adaptors/pss/translator/COPCHandlingIT.java, gp2gp-translator/src/integrationTest/java/uk/nhs/adaptors/pss/translator/FailedProcessHandingIT.java, gp2gp-translator/src/integrationTest/java/uk/nhs/adaptors/pss/translator/LargeMessagingIT.java, gp2gp-translator/src/integrationTest/java/uk/nhs/adaptors/pss/translator/amqp/ServiceFailureIT.java, gp2gp-translator/src/integrationTest/java/uk/nhs/adaptors/pss/util/BaseEhrHandler.java
sendInboundMessageToQueue and fetchMessageInJsonFormat
=> Refactor: Pull share methods up into BaseEhrHandler

gp2gp-translator/src/integrationTest/java/uk/nhs/adaptors/pss/translator/EhrExtractHandlingIT.java
Reduces a whole lot of duplication within EhrExtractHandlingIT
=> Refactor: Use BaseEhrHandler methods from EhrExtractHandlingIT

gp2gp-translator/src/integrationTest/java/uk/nhs/adaptors/pss/translator/FailedProcessHandingIT.java, gp2gp-translator/src/integrationTest/java/uk/nhs/adaptors/pss/translator/FailedProcessHandlingIT.java, gp2gp-translator/src/integrationTest/java/uk/nhs/adaptors/pss/util/BaseEhrHandler.java
1. Makes some methods more reusable
2. Makes some code more readable
=> Refactor: Simplify FailedProcessHandlingIT

gp2gp-translator/src/integrationTest/java/uk/nhs/adaptors/pss/translator/FailedProcessHandlingIT.java, gp2gp-translator/src/integrationTest/java/uk/nhs/adaptors/pss/util/BaseEhrHandler.java
=> Refactor: Pull sendNackToQueue up to BaseEhrHandler

gp2gp-translator/src/integrationTest/java/uk/nhs/adaptors/pss/translator/AcknowledgeMessageHandlingIT.java, gp2gp-translator/src/integrationTest/java/uk/nhs/adaptors/pss/translator/service/AcknowledgeRecordServiceIT.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/ConditionMapperTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/TemplateMapperTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/mapper/medication/MedicationRequestPlanMapperTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/task/SendACKMessageHandlerTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/task/SendNACKMessageHandlerTest.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/util/CompoundStatementUtilTest.java
Removing excessive or unused code
There are some excessive or unused code that needed to be cleaned
=> Removing excessive or unused code

gp2gp-translator/src/integrationTest/java/uk/nhs/adaptors/pss/translator/COPCHandlingIT.java, gp2gp-translator/src/integrationTest/java/uk/nhs/adaptors/pss/translator/E2EMappingIT.java, gp2gp-translator/src/integrationTest/java/uk/nhs/adaptors/pss/translator/EhrExtractHandlingIT.java, gp2gp-translator/src/integrationTest/java/uk/nhs/adaptors/pss/translator/FailedProcessHandlingIT.java, gp2gp-translator/src/integrationTest/java/uk/nhs/adaptors/pss/translator/LargeMessagingIT.java, gp2gp-translator/src/integrationTest/java/uk/nhs/adaptors/pss/translator/amqp/ServiceFailureIT.java, gp2gp-translator/src/integrationTest/java/uk/nhs/adaptors/pss/util/BaseEhrHandler.java
See individual commits for each change.
=> Refactor: Improve clarity of Integration Test failure messages when awaiting for Migration Status

settings.gradle
=> Rename gradle project to gp2gp-fhir-request-adaptor

gp2gp-translator/build.gradle, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/storage/AWSStorageService.java, gp2gp-translator/src/main/java/uk/nhs/adaptors/pss/translator/storage/StorageServiceFactory.java, gp2gp-translator/src/test/java/uk/nhs/adaptors/pss/translator/storage/AWSStorageServiceTest.java
Migration from AWS SDK 1 to AWS SDK 2
Upgrading from AWS SDK 1 to AWS SDK 2 is beneficial because the newer version offers several improvements in functionality, performance and design.
=> NIAD-3264: migration from AWS SDK 1 to AWS SDK 2

gp2gp-translator/src/integrationTest/java/uk/nhs/adaptors/pss/translator/E2EMappingIT.java, gp2gp-translator/src/integrationTest/java/uk/nhs/adaptors/pss/util/BaseEhrHandler.java, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP10-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP11-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP2-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP3-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP4-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP5-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP6-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP7_vis-output.json, gp2gp-translator/src/integrationTest/resources/e2e-mapping/output-json/PWTP9-output.json
=> Refactor: Simplify the E2EMappingIT tests

CHANGELOG.md
=> Release 3.0.9

db-connector/src/main/java/uk/nhs/adaptors/connector/dao/PatientMigrationRequestDao.java, db-connector/src/main/java/uk/nhs/adaptors/connector/service/MigrationStatusLogService.java, db-connector/src/test/java/uk/nhs/adaptors/connector/service/MigrationStatusLogServiceTest.java, gp2gp-translator/src/integrationTest/java/uk/nhs/adaptors/pss/translator/amqp/ServiceFailureIT.java, gp2gp-translator/src/integrationTest/java/uk/nhs/adaptors/pss/translator/task/scheduled/EHRTimeoutHandlerIT.java, gpc-api-facade/src/main/java/uk/nhs/adaptors/pss/gpc/service/PatientTransferService.java, gpc-api-facade/src/test/java/uk/nhs/adaptors/pss/gpc/service/PatientTransferServiceTest.java
=> NIAD-3269: Fixing getMigrationRequestId throwing exception

getting-started-instructions.md
=> Configure SDS as part of Requesting Adaptor getting started insturctions

getting-started-instructions.md
Think the instructions will be helped by the addition of a visualisation.
=> Add container diagrams to getting-started-instructions.md

.github/workflows/build.yml
=> Rename workflow to "Build" to reduce the space it takes up

CHANGELOG.md
=> release 3.0.10
